python:
    - 3.8

# macos_min_version:
#   - 10.9
# macos_machine:
#   - x86_64-apple-darwin13.4.0
# MACOSX_DEPLOYMENT_TARGET:
#   - 10.9
# CONDA_BUILD_SYSROOT:            # [osx]
#   - /         # [osx]
