{% set name = "TraceInv" %}
{% set data = load_setup_py_data() %}

package:
    name: "{{ name|lower }}"
    version: "{{ data['version'] }}"

source:
    path: ..

# source:
#   url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
    number: 0
    script: 
        - export SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk; {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
        # - export CFLAGS="${CFLAGS} -isysroot ${CONDA_BUILD_SYSROOT}"; {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
        # - {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
        # - python setup.py install
        # - brew install libomp   # [osx]
        # - export LDFLAGS=-L/usr/local/opt/libomp/lib   # [osx]
    # script: # - python setup.py install . --single-version-externally-managed --record=record.txt -vvv
    # script: {{ PYTHON }} -m pip install . --single-version-externally-managed --record=record.txt --no-deps --ignore-installed --no-cache-dir -vvv
    # script: "{{ PYTHON }} -m pip install . -vv"
    features:
        - vc9               [win and py27]
        - vc10              [win and py34]
        - vc14              [win and py35]

requirements:
    build:
        - {{ compiler('c') }}
        - llvm-openmp  # [osx]

    host:
        - python {{ python }}
        - setuptools
        - numpy>1.11
        - cython>0.29
        - pip
        # - pytest-runner
        # - suitesparse
        # - scipy
        # - matplotlib
        # - seaborn
    run:
        - python {{ python }}
        - numpy>1.11
        - scipy
        # - suitesparse
        - matplotlib
        - seaborn
        # - cython
        # - setuptools
        # - llvm-openmp  # [osx]

test:
    imports:
        - TraceInv
        - TraceInv.ComputeLogDeterminant
        - TraceInv.ComputeTraceOfInverse
        - TraceInv.GenerateMatrix
        - TraceInv.InterpolateTraceOfInverse
    requires:
        - pytest
        - pytest-cov
        - pytest-runner

about:
    home: {{ data['url'] }}
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: {{ data['description'] }}
    description: {{ data['description'] }}
    doc_url: https://ameli.github.io/TraceInv/index.html
    doc_source_url: https://github.com/ameli/TraceInv/blob/main/README.rst
    dev_url: https://github.com/ameli/TraceInv

extra:
    recipe-maintainers:
        - ameli
