name: deploy-docs

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Install Prerequisit
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install --upgrade sphinx
                  which sphinx
                  which sphinx-apidoc

            - name: Build and Deploy
              uses: JacksonMaxfield/github-pages-deploy-action-python@master
              env:
                  ACCESS_TOKEN: ${{ secrets.TRACEINV_DOCS }}
                  BASE_BRANCH: master
                  BRANCH: gh-pages
                  FOLDER: docs/_build/html
                  BUILD_SCRIPT: |
                      export PATH=${PATH}:/home/runner/.local/bin
                      ls /home/runner/.local/bin
                      sphinx-apidoc -f -o docs/_modules/ ./TraceInv
                      make -C docs/ html
                      touch docs/_build/html/.nojekyll
                      echo 'Visit [Documentation](https://ameli.github.io/TraceInv/index.html).' > docs/_build/html/README.md

