# name: deploy-conda
#
# on:
#     push:
#         branches:
#             - main
#     release:
#         types: [published]
#     
# jobs:
#     publish:
#         runs-on: ubuntu-latest
#         name: Publish to Conda
#         steps:
#             - name: Checkout
#               uses: actions/checkout@v2
#
#             - name: publish-to-conda
#               uses: fcakyon/conda-publish-action@v1.3
#               with:
#                   subdir: 'conda'
#                   anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
#                   platforms: 'win osx linux'
#               env:
#                   CYTHON_BUILD_IN_SOURCE: 'true'

name: deploy-conda

on:
    push:
        branches:
            - main
    release:
        types: [published]

jobs:
    build:

        runs-on: ubuntu-latest
        # strategy:
        #     matrix:
        #         python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            # - name: Set up Python ${{ matrix.python-version }}
            - name: Set up Python
              uses: actions/setup-python@v2
              # with:
              #     python-version: ${{ matrix.python-version }}

            - name: Install prerequisits
              run: |
                  sudo apt-get update
                  sudo apt-get install libsuitesparse-dev

            - name: Install package and dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install --upgrade numpy
                  # python -m pip install --upgrade .[full]

            - name: Install conda, conda-build, and conda-client
              run: |
                  wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
                  bash miniconda.sh -b -p $HOME/miniconda
                  export PATH="$HOME/miniconda/bin:$PATH"
                  hash -r
                  conda config --set always_yes yes --set changeps1 no
                  conda update -q conda
                  conda install conda-build
                  conda install anaconda-client
                  which conda-build

            - name: Build and upload to Anaconda cloud
              run: |
                  which conda-build
                  conda config --set anaconda_upload yes
                  conda-build --token ${{ secrets.ANACONDA_TOKEN }} .
              env:
                  CYTHON_BUILD_IN_SOURCE: 'true'

              # $(conda info --root)/conda-bld
